./configure \
--enable-cross-compile \
--cross-prefix=i386-mingw32- \
--target-os=mingw32 \
--arch=i386 \
--enable-memalign-hack \
--enable-shared \
--disable-static \
--enable-version3 \
--enable-libmp3lame \
--enable-libopencore-amrnb \
--enable-libopencore-amrwb \
--enable-encoder=png \
--prefix=raybuild_shared
